### ISSUE TITLE
IndexError - index 21 out of string:

### ISSUE THREAD

**Issue by afics** [ytti/oxidized-web#159]
Happens when accessing ```https://oxidized.example.com/node/version/diffs?node=router01&group=group01&oid=245d5f3ccc08f18b1aaa85d8663b1ed4af6e680b&date=2018-03-22```.
Backtrace:
```
/home/oxidized/gemhome/gems/oxidized-web-0.9.3/lib/oxidized/web/webapp.rb:264:in `insert'
/home/oxidized/gemhome/gems/oxidized-web-0.9.3/lib/oxidized/web/webapp.rb:264:in `time_from_now'
/home/oxidized/gemhome/gems/oxidized-web-0.9.3/lib/oxidized/web/views/diffs.haml:45:in `block in singleton c
/home/oxidized/gemhome/gems/oxidized-web-0.9.3/lib/oxidized/web/views/diffs.haml:-9:in `instance_eval'
/home/oxidized/gemhome/gems/oxidized-web-0.9.3/lib/oxidized/web/views/diffs.haml:-9:in `singleton class'
/home/oxidized/gemhome/gems/oxidized-web-0.9.3/lib/oxidized/web/views/diffs.haml:-12:in `__tilt_471844218530
/home/oxidized/gemhome/gems/tilt-2.0.8/lib/tilt/template.rb:170:in `call'
/home/oxidized/gemhome/gems/tilt-2.0.8/lib/tilt/template.rb:170:in `evaluate'
/home/oxidized/gemhome/gems/tilt-2.0.8/lib/tilt/haml.rb:46:in `evaluate'
/home/oxidized/gemhome/gems/tilt-2.0.8/lib/tilt/template.rb:109:in `render'
/home/oxidized/gemhome/gems/sinatra-1.4.8/lib/sinatra/base.rb:823:in `render'
/home/oxidized/gemhome/gems/sinatra-1.4.8/lib/sinatra/base.rb:677:in `haml'
/home/oxidized/gemhome/gems/oxidized-web-0.9.3/lib/oxidized/web/webapp.rb:237:in `out'
/home/oxidized/gemhome/gems/oxidized-web-0.9.3/lib/oxidized/web/webapp.rb:216:in `block in <class:WebApp>'
/home/oxidized/gemhome/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `call'
/home/oxidized/gemhome/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `block in compile!'
/home/oxidized/gemhome/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
/home/oxidized/gemhome/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval'
/home/oxidized/gemhome/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
/home/oxidized/gemhome/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route'
/home/oxidized/gemhome/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `catch'
/home/oxidized/gemhome/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'
/home/oxidized/gemhome/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `block in route!'
/home/oxidized/gemhome/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `each'
/home/oxidized/gemhome/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `route!'
/home/oxidized/gemhome/gems/sinatra-1.4.8/lib/sinatra/base.rb:1085:in `block in dispatch!'
/home/oxidized/gemhome/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
/home/oxidized/gemhome/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
/home/oxidized/gemhome/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
/home/oxidized/gemhome/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!'
/home/oxidized/gemhome/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'
/home/oxidized/gemhome/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
/home/oxidized/gemhome/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
/home/oxidized/gemhome/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
/home/oxidized/gemhome/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!'
/home/oxidized/gemhome/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call'
/home/oxidized/gemhome/gems/rack-protection-1.5.5/lib/rack/protection/xss_header.rb:18:in `call'
/home/oxidized/gemhome/gems/rack-protection-1.5.5/lib/rack/protection/path_traversal.rb:16:in `call'
/home/oxidized/gemhome/gems/rack-protection-1.5.5/lib/rack/protection/json_csrf.rb:18:in `call'
/home/oxidized/gemhome/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
/home/oxidized/gemhome/gems/rack-protection-1.5.5/lib/rack/protection/frame_options.rb:31:in `call'
/home/oxidized/gemhome/gems/rack-1.6.9/lib/rack/nulllogger.rb:9:in `call'
/home/oxidized/gemhome/gems/rack-1.6.9/lib/rack/head.rb:13:in `call'
/home/oxidized/gemhome/gems/sinatra-1.4.8/lib/sinatra/show_exceptions.rb:25:in `call'
/home/oxidized/gemhome/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'
/home/oxidized/gemhome/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'
/home/oxidized/gemhome/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `block in call'
/home/oxidized/gemhome/gems/sinatra-1.4.8/lib/sinatra/base.rb:1787:in `synchronize'
/home/oxidized/gemhome/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `call'
/home/oxidized/gemhome/gems/rack-1.6.9/lib/rack/urlmap.rb:66:in `block in call'
/home/oxidized/gemhome/gems/rack-1.6.9/lib/rack/urlmap.rb:50:in `each'
/home/oxidized/gemhome/gems/rack-1.6.9/lib/rack/urlmap.rb:50:in `call'
/home/oxidized/gemhome/gems/rack-1.6.9/lib/rack/builder.rb:153:in `call'
/home/oxidized/gemhome/gems/puma-3.11.3/lib/puma/configuration.rb:225:in `call'
/home/oxidized/gemhome/gems/puma-3.11.3/lib/puma/server.rb:624:in `handle_request'
/home/oxidized/gemhome/gems/puma-3.11.3/lib/puma/server.rb:438:in `process_client'
/home/oxidized/gemhome/gems/puma-3.11.3/lib/puma/server.rb:302:in `block in run'
/home/oxidized/gemhome/gems/puma-3.11.3/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

**Comment by laf** [comment]
Looks like it's because only the yyyy-mm-dd gets called.

Here's what my url looks like: `node/version/diffs?node=rtr01&group=default&oid=f93417d7a126246d4827ca5ef0e729d28a8f40ea&date=2018-02-17%2023:05:59%20+0000&num=8`.

How are you accessing that link?
